config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :password_resets, except: [:show, :destroy, :index]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers #  /users/1/following
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # dependent microposts to be destroyed when the user itself is destroyed
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  def self.digest string
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create string, cost: cost
  end

  def self.new_token #  create a token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    # save digest of token into DB bypass validates
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false unless digest
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  # Activates an account.
  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def self.select_user_activated
    User.where activated: true
  end

  # Sets the reset_token and update reset_digest attributes into DB
  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes(reset_digest: User.digest(reset_token),
      reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    # default following_ids return a array followed user'id = user.following.map(&:id)
    # but it's bad with 5000 followed user because user.following is a array and
    # map with get each element of array. so use sql command to faster. but id
    # not avalible in eveytime so need to pass into following_ids + user_id in
    # where command also need to pass in, so use :user_id for both
    following_ids = "SELECT followed_id FROM relationships
      WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id",
      user_id: id) # self.id
  end

  def follow other_user
    following << other_user # add element into array
  end

  # Unfollows a user.
  def unfollow other_user
    following.delete other_user # delete element out of array
  end

  # Returns true if the current user is following the other user.
  def following? other_user
    following.include? other_user # check array are there include other_user?
  end

  def followers? other_user
    followers.include? other_user # check array are there include other_user?
  end

  private

  # Converts email to all lower-case - standard for email in DB
  def downcase_email
    email.downcase!
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest # called by before_create so auto save into DB
    self.activation_token  = User.new_token # vitrual abttribute
    self.activation_digest = User.digest activation_token # abttribute in DB
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %I[new index create]
  before_action :logged_in_user,
    only: %I[index edit update destroy following followers] # an array of symbol
  before_action :correct_user, only: %I[edit update] # only edit their infor
  before_action :admin_user, only: :destroy

  def index
    @users = User.select_user_activated.paginate page: params[:page], :per_page => 10
  end

  def show
    @microposts = @user.microposts.paginate page: params[:page], :per_page => 5
    return if @user.activated?
    flash[:danger] = t "controller.user.error_activate"
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create # post
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "controller.user.create.info"
      redirect_to root_url
    else
      render :new # haven't a view for create action, so must render new view
    end
  end

  def edit; end

  def update # patch
    if @user.update_attributes user_params
      flash[:success] = t "controller.user.updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controller.user.destroy.success"
      redirect_to users_url
    else
      flash[:danger] = t "controller.user.destroy.danger"
      redirect_to root_url
    end
  end

  def following
    @title = t "controller.user.following.title"
    @user = User.find_by id: params[:id]
    if @user
      @users = @user.following.paginate page: params[:page], :per_page => 10
      render "show_follow"
    else
      redirect_to root_url
    end
  end

  def followers
    @title = t "controller.user.followers.title"
    @user = User.find_by id: params[:id]
    if @user
      @users = @user.followers.paginate page: params[:page], :per_page => 10
      render "show_follow"
    else
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id] # request to other user
    return if @user
    flash[:danger] = t "controller.user.error_id"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for user, hash_size = {size: 80}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = hash_size[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_follow.html.erb
<!-- Returns a new Relationship object with follower_id = user's id
  remote: true tells Rails to allow the form to be handled by JavaScript.-->
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("user.follow.follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- when access another user's profile @so @user = other user = use of show
  action, current_user is loged in, so it is defferrent that block will excuse -->
<% unless current_user? @user %>
  <div id="follow_form">
  <% if current_user.following? @user %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name, t("user.form.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t("user.form.email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t("user.form.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("user.form.confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<!-- return a active_relationships. Rails auto uses Ajax with remote: true -->
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
  html: {method: :delete}, remote: true) do |f| %>
  <%= f.submit t("user.unfollow.unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t("user.user.delete"), user, method: :delete,
      data: {confirm: t("user.user.confirm")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, t("user.edit.title")) %>
<% provide(:button_text, t("user.edit.save")) %>
<h1><%= t"user.edit.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- @user.new_record? to rails know to use a post or patch (post + a hidden
    input field) -->
    <%= render "form", url: {url: user_path} %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">
        <%= t"user.edit.change" %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t("user.index.title")) %>
<h1>A<%= t"user.index.title" %></h1>
<!-- method of gem will_paginate need paginate method paginate the users for it active,it automatically looks for an @users, then displays pagination links to access other pages. if users < default 30 will not display pagination-->
<%= will_paginate %>
<ul class="users">
<!-- Rails auto iterates through them and renders each one with the _user.html.erb -->
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, t("user.new.title")) %>
<% provide(:button_text, t("user.new.create")) %>
<h1><%= t"user.new.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- @user is new object of User class => action /user , method post and
    create 1 user hash include list of key wihch are arguments of input element,
    these arguments are attributes of User class -->
    <%= render "form", url: {url: signup_path} %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form" if logged_in? %><!-- access profile of other user -->
    <% if @user.microposts.any? %>
      <h3><%= t "user.show.microposts"%>(<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t("user.show_follow.view"), @user %></span>
      <span><b><%= t"user.show_follow.icroposts" %></b>
        <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %><!-- user.following -->
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>