config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :password_resets, except: [:show, :destroy, :index]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers #  /users/1/following
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<!-- the underscore of name is the universal convention for naming partials to
  identify all the partials in a directory at a glance. -->
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/"><%= t"footer.rails_tut" %></a>
    <%= t"footer.by" %><a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("footer.about"), about_path %></li>
      <li><%= link_to t("footer.contact"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t"footer.news" %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("header.sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("header.home"), root_path %></li>
        <li><%= link_to t("header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("header.users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t"header.account"%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("header.profile"), current_user %></li>
              <li><%= link_to t("header.settings"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to  t("header.logout"), logout_path, method: :delete%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>